# Generated by Django 4.2.1 on 2023-06-12 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Введен некорректный номер телефона', regex='^7\\d{10}$')], verbose_name='Номер телефона клиента')),
                ('mobile_operator_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Введен некорректный код оператора', regex='^.{3}$')], verbose_name='Код мобильного оператора')),
                ('client_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тэг клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('mobile_operator_code', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Введен некорректный код оператора', regex='^.{3}$')], verbose_name='Код мобильного оператора')),
                ('client_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тэг клиента')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время запуска')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания (отправки)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_sender.client', verbose_name='id клиента')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_sender.mailing', verbose_name='id рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
