# Generated by Django 4.2.1 on 2023-05-25 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Введен некорректный номер телефона', regex='^7\\d{10}$'), django.core.validators.MinLengthValidator(limit_value=3, message='Недостаточно символов')], verbose_name='Код мобильного оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Введен некорректный номер телефона', regex='^7\\d{10}$'), django.core.validators.MinLengthValidator(limit_value=3, message='Недостаточно символов')], verbose_name='Номер телефона клиента'),
        ),
    ]
