# Generated by Django 4.2.1 on 2023-05-25 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Введен некорректный номер телефона', regex='^.{3}$')], verbose_name='Код мобильного оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Введен некорректный номер телефона', regex='^7\\d{10}$')], verbose_name='Номер телефона клиента'),
        ),
    ]
