# Generated by Django 4.2.1 on 2023-05-26 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_sender', '0003_alter_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Введен некорректный код оператора', regex='^.{3}$')], verbose_name='Код мобильного оператора'),
        ),
    ]
