version: '3'
services:

#  db:
#    image: postgres:14.6-alpine
#    environment:
#      - POSTGRES_DB=mailing_service
#      - POSTGRES_USER=dbuser
#      - POSTGRES_PASSWORD=pass
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data/
#    ports:
#      - '5432'
#    networks:
#      - djangonetwork

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/mailing_service
    environment:
      - DB_HOST=db
      - DB_NAME=mailing_service
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - db
#    networks:
#      - djangonetwork

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    depends_on:
#      - db
      - web-app
#    networks:
#      - djangonetwork

  celery_worker:
    build:
      context: .
    hostname: celery_worker
    command: celery -A messaging_service worker -l info
    volumes:
      - .:/mailing_service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - redis
    depends_on:
#      - db
      - web-app
      - redis
#    networks:
#      - djangonetwork

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A messaging_service flower
    volumes:
      - .:/mailing_service
    links:
      - redis
    depends_on:
#      - db
      - web-app
      - redis
    ports:
      - "5555:5555"
#    networks:
#      - djangonetwork

#networks:
#  djangonetwork:
#    driver: bridge